name: avatar_env

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.8
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - cudnn=8.3.2
  - librosa=0.10.0
  - numpy=1.23.0
  - scipy=1.10.1
  - pysoundfile=0.12.1
  - python-sounddevice=0.3.12
  - pip
  - pip:
      - ctranslate2==3.13.0
      - datasets==2.12.0
      - faster-whisper==0.5.1
      - inflect==6.0.4
      - pygame==2.4.0
      - sentencepiece==0.1.99
      - tensorflow-cpu==2.12.0
      - transformers==4.28.1
